name    'puppet-openldap'
version '0.0.1'
source 'git://github.com/kleinmann/puppet-openldap'
author 'Uwe Kleinmann'
summary 'Puppet module for openldap server and client'
description 'Puppet module for openldap server and client'
license 'BSD'
project_page 'https://github.com/kleinmann/puppet-openldap'
